/**
 * @file attr_table.h
 *
 * @brief This is generated by attribute_generator.py
 *
 * Copyright (c) 2021 Laird Connectivity
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __ATTRIBUTE_TABLE_H__
#define __ATTRIBUTE_TABLE_H__

/******************************************************************************/
/* Includes                                                                   */
/******************************************************************************/
#include <zephyr.h>
#include <zephyr/types.h>
#include <stddef.h>

#include "attr_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* Indices                                                                    */
/******************************************************************************/

/* pystart - attribute indices */
#define ATTR_INDEX_lock                               5
#define ATTR_INDEX_load_path                          9
/* pyend */

/* pystart - attribute ids */
#define ATTR_ID_sensor_name                           0
#define ATTR_ID_location                              1
#define ATTR_ID_advertising_interval                  2
#define ATTR_ID_advertising_duration                  3
#define ATTR_ID_passkey                               4
#define ATTR_ID_lock                                  5
#define ATTR_ID_up_time                               16
#define ATTR_ID_qrtc                                  94
#define ATTR_ID_qrtc_last_set                         95
#define ATTR_ID_load_path                             208
#define ATTR_ID_dump_path                             209
/* pyend */

/******************************************************************************/
/* Constants and Enumerations                                                 */
/******************************************************************************/

/* pystart - attribute constants */
#define ATTR_TABLE_SIZE                               11
#define ATTR_TABLE_MAX_ID                             209
#define ATTR_TABLE_WRITABLE_COUNT                     8
#define ATTR_MAX_STR_LENGTH                           32
#define ATTR_MAX_STR_SIZE                             33
#define ATTR_MAX_BIN_SIZE                             8
#define ATTR_MAX_INT_SIZE                             8

/* Attribute Max String Lengths */
#define ATTR_SENSOR_NAME_MAX_STR_SIZE                 24
#define ATTR_LOCATION_MAX_STR_SIZE                    33
#define ATTR_LOAD_PATH_MAX_STR_SIZE                   33
#define ATTR_DUMP_PATH_MAX_STR_SIZE                   33

/* Attribute Byte Array Lengths */
/* pyend */

/* pystart - enumerations */
/* pyend */

/* Enums used by Management Commands */
enum attr_dump {
	ATTR_DUMP_RW = 0,
	ATTR_DUMP_W = 1,
	ATTR_DUMP_RO = 2,
};

/* pystart - enum size check */
/* pyend */

/******************************************************************************/
/* Global Function Prototypes                                                 */
/******************************************************************************/
/* The weak implementations should be overridden in application. */
/* pystart - prepare for read */
int attr_prepare_up_time(void);
int attr_prepare_qrtc(void);
int attr_prepare_qrtc_last_set(void);
/* pyend */

/* pystart - get string */
/* pyend */

#ifdef __cplusplus
}
#endif

#endif /* __ATTRIBUTE_TABLE_H__ */
